# Workflow to release a new version of the project using semantic-release.
name: release

# This workflow can be triggered manually using 'workflow_dispatch'
# or automatically on a push to the 'main' branch.
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Define the permissions for the workflow.
# Note: The workflow needs to have write permissions to the repository to create tags and releases.
permissions:
  # To create a release.
  contents: write
  # To write comments to issues.
  issues: write
  # To write comments to PRs.
  pull-requests: write

# Define the jobs that will run.
jobs:
  release:
    uses: gucasassi/gha-reusable/.github/workflows/semantic-release.yml@main
    secrets: inherit
